# Generated by Django 3.2.14 on 2022-07-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_auto_20220729_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sketchfab_embed_code',
            field=models.TextField(blank=True, null=True, verbose_name='SketchfabEmbedCode'),
        ),
    ]
